// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCknzp_FqAmh4ZKr25xtcwNtJWlSNK8Ru4',
    appId: '1:1098635578493:web:c6835f91e74404afdbb514',
    messagingSenderId: '1098635578493',
    projectId: 'esteticaauto-98136',
    authDomain: 'esteticaauto-98136.firebaseapp.com',
    storageBucket: 'esteticaauto-98136.firebasestorage.app',
    measurementId: 'G-TDGY31NWKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtZSttHSy8xVOsQYwxQdCcIn0UcxDVZLs',
    appId: '1:1098635578493:android:9f0ebe0e062ada6fdbb514',
    messagingSenderId: '1098635578493',
    projectId: 'esteticaauto-98136',
    storageBucket: 'esteticaauto-98136.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAPOgHf4AYDlmXbaHoBCds7BXYnNtKRHc',
    appId: '1:1098635578493:ios:809c271db7f16b2edbb514',
    messagingSenderId: '1098635578493',
    projectId: 'esteticaauto-98136',
    storageBucket: 'esteticaauto-98136.firebasestorage.app',
    iosBundleId: 'com.example.esteticaAuto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAPOgHf4AYDlmXbaHoBCds7BXYnNtKRHc',
    appId: '1:1098635578493:ios:809c271db7f16b2edbb514',
    messagingSenderId: '1098635578493',
    projectId: 'esteticaauto-98136',
    storageBucket: 'esteticaauto-98136.firebasestorage.app',
    iosBundleId: 'com.example.esteticaAuto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCknzp_FqAmh4ZKr25xtcwNtJWlSNK8Ru4',
    appId: '1:1098635578493:web:2f96f4bd8f659edddbb514',
    messagingSenderId: '1098635578493',
    projectId: 'esteticaauto-98136',
    authDomain: 'esteticaauto-98136.firebaseapp.com',
    storageBucket: 'esteticaauto-98136.firebasestorage.app',
    measurementId: 'G-HT5WV0E044',
  );

}